Repository chaostoolkit/chaostoolkit-lib, pull requests merged in 2019-03, with the labels that each got.

#84 Add range tolerance
  CHANGELOG.md
  chaoslib/hypothesis.py
  tests/test_tolerance.py
Labels: core, enhancement

#89 Corrected logic around activity-level control application.
  CHANGELOG.md
  chaoslib/control/__init__.py
  tests/fixtures/experiments.py
  tests/test_control.py
Labels: bug

#91 Do not fail validation when control module is missing
  CHANGELOG.md
  chaoslib/control/python.py
  tests/test_control.py
Labels: enhancement, feature:run
