Repository chaostoolkit/chaostoolkit-lib, pull requests merged in 2019-04, with the labels that each got.

#101 Added ignore statement for Pycharm artifacts.
  .gitignore
Labels: enhancement

#100 Fix tolerance probe
  CHANGELOG.md
  chaoslib/hypothesis.py
  tests/fixtures/probes.py
  tests/test_tolerance.py
Labels: core

#109 Load controls from settings
  CHANGELOG.md
  chaoslib/control/__init__.py
  chaoslib/control/python.py
  chaoslib/settings.py
  setup.py
  tests/fixtures/controls/dummy.py
  tests/fixtures/controls/dummy_with_experiment.py
  tests/fixtures/experiments.py
  tests/test_control.py
  tests/test_settings.py
Labels: core, enhancement

#112 Corrected typo
  chaoslib/provider/process.py
Labels: enhancement

#113 Corrected typo in docstring
  chaoslib/activity.py
Labels: enhancement
